# serverless/serverless.yml

service: my-go-lambda

provider:
  name: aws
  runtime: provided.al2
  region: us-east-1

functions:
  hello:
    handler: bootstrap
    events:
      - http:
          path: hello
          method: get
  api:
    handler: bootstrap
    events:
      - http:
          path: api
          method: get

package:
  artifact: bin/hello.zip
  artifact: bin/api.zip

custom:
  scriptable:
    hooks:
      before:package:createDeploymentArtifacts: make build

plugins:
  - serverless-scriptable-plugin
